version: '3.8'

services:
  db:
    image: postgres:15
    container_name: subscriptions_db
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: subscriptions_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscribe_aggregation_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=web
      - DB_PASSWORD=examplepassword
      - DB_NAME=subscriptions_db
    ports:
      - "8080:8080"

volumes:
  pgdata:
